---
title: "Lab Week 8-Github"
author: "Susan Mazer"
date: "3/8/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(sf)
library(tmap)
library(leaflet)
library(spatstat)
library(maptools)
library(corrplot)
```

```{r}
oil_spills <- read_csv("oil_spills.csv")

df <- oil_spills %>%
  filter(`Accident State` == "TX" & `Accident Year`< 2017) %>%
  group_by(`Accident Year`) %>%
  summarise(Loss = sum(`Net Loss (Barrels)`))

colnames(df) <- c("Year","Loss")

ggplot(df, aes(x = Year, y = Loss)) +
  geom_col()


```
#right-slanted apostrophe is the lower character of the "~"" key.

##Make a new dataframe; a leflet polot of spill locations in TX in 2016.

```{r}

df_loc <- oil_spills %>%
  filter(`Accident State` == "TX" & `Accident Year` == 2016) %>%
  select(Latitude, Longitude, `Net Loss (Barrels)`)
         
  colnames(df_loc) <- c("latitude", "longitude", "net_loss")
  
  oil_sf <- st_as_sf(df_loc, coords = c("longitude","latitude"), crs = 4326)
  
  leaflet(oil_sf) %>%
    addTiles() %>%
    addMarkers()
```

## tmap plot with the Texas state shapefile

```{r}

states <- st_read(dsn = ".", layer = "states")

tex_border <- states %>%
  filter(STATE_NAME == "Texas") %>%
  st_transform(4326)

#Now, the coordinate reference system matches that of texas border points

plot(tex_border)

tm_shape(tex_border) +
  tm_polygons() +
  tm_shape(oil_sf) +
  tm_dots(size = 0.3)
```

###Convert the data to spatial points patterns (combination of point data and the bounding window)

```{r}

#Convert back from simple features back to data frame

spill_sp<- as(oil_sf, "Spatial")

#but this still isn't something that R recognizes that R can use for spatial points patterns.  Will makes something called ppp ("point pattern analysis")

spill_ppp <- as(spill_sp, "ppp")

#specify bounding, which will be Texas boundary

tx_sp <- as(tex_border, "Spatial")

#makes tex_border a spatial dataframe

tx_owin <- as(tx_sp, "owin")

#makes tx_sp and "owin" file

all_ppp <- ppp(spill_ppp$x, spill_ppp$y, window = tx_owin)
```

###A density plot indicating the locations of the most densely distributed points:

```{r}

plot(density(all_ppp, sigma = 0.4))

#0.4 is the radius of the bubbles around oil spills
```

###Quadrat test
```{r}
oil_qt <- quadrat.test(all_ppp, nx = 5, ny = 5)

#Takes state of texas and divides it into a grid 5 quads high and 5 quads wide; then tests using chi-square to test null hypothesis that  the distribution of points is random (Complete spatial randomness)

oil_qt

#The output demonstrates that the data are *not* CSR

plot(all_ppp)

plot(oil_qt, add = TRUE, cex = 0.4) #cex changes font size

#The resulting grid with points shows the number of points (upper right) that would be expected in each quadrant in the case of CSR and whether the actual number is.  Upper left shows the number of actual counts.  In the center/bottom is a standardized measure of how much lower/higher the actual number is relative to the expected number

lag<-seq(0, 1, b = 0.01)

oil_gfun <- envelope(all_ppp, fun=Gest, r = lag, nsim = 100)

ggplot(oil_gfun, aes(x = r, y = obs)) +
  geom_line(color = "black") +
  geom_line(aes(x = r, y = theo), color = "red")

#The plot shows that our data have more nearest-neighbor points that are closer than expected based on completely spatially random data

```

